// <auto-generated />
namespace Smart_heaters_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Models_Controllers_Created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Models_Controllers_Created));
        
        string IMigrationMetadata.Id
        {
            get { return "202011211427425_Models_Controllers_Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
