// <auto-generated />
namespace Smart_heaters_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModelReadings_Edited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModelReadings_Edited));
        
        string IMigrationMetadata.Id
        {
            get { return "202011221050226_ModelReadings_Edited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
